//pointer to function...
#include<stdio.h>
void fun1(int a,int b);// declaring a function...

void fun1(int a,int b){ // defining that function....
	printf("\n%d %d",a,b);
}

int main(){
	void (*fun2)()=fun1;// passing the address of that function to another pointer function...
	
	
	(*fun2)(4,2);//calling function via function pointer....
	return 0;
}
